CREATE TABLE levell(STUDENT_ID INTEGER PRIMARY KEY,NAME VARCHAR(100));
CREATE TABLE STUDENT(STUDENT_ID INTEGER PRIMARY KEY,NAME VARCHAR (100),EMAIL TEXT,PHONE INTEGER, LEVEL_ID INTEGER REFERENCES levell (STUDENT_ID));
CREATE TABLE EXAM (STUDENT_ID INTEGER PRIMARY KEY,DATEE DATE);
CREATE TABLE SUBJECT(STUDENT_ID INTEGER PRIMARY KEY,NAME VARCHAR (100),SUB_DESC TEXT,MAX_SCORE INTEGER);
CREATE TABLE STU_SUBJECTS(STU_ID INTEGER  REFERENCES STUDENT(STUDENT_ID),SUB_ID INTEGER REFERENCES SUBJECT(STUDENT_ID),PRIMARY KEY(STU_ID,SUB_ID));
CREATE TABLE STU_GRADES(STU_ID INTEGER  REFERENCES STUDENT(STUDENT_ID),SUB_ID INTEGER REFERENCES SUBJECT(STUDENT_ID),PRIMARY KEY(STU_ID,SUB_ID));
insert into levell (student_id,name) values (1,'one'),
(2,'two'),(3,'three');
    alter table student
    add COLUMN gender text;
    alter table student
    add COLUMN birth_d DATE;
    INSERT INTO student (STUDENT_ID,name, email, phone, level_id,birth_d,gender)
VALUES
    (1,'John Doe', 'john@example.com', '123790', 1,'2000-12-12','MALE'),
    (2,'Alice Adams', 'alice@example.com', '9810', 2,'1990-12-10','FEMALE'),
    (3,'Bob Smith', 'bob@example.com', '55567', 1,'1980-09-08','MALE');
    INSERT INTO SUBJECT(STUDENT_ID,NAME,SUB_DESC,MAX_SCORE) VALUES(1,'ENGLISH','EXCELLENT',90),
    (2,'ARABIC','GOOD',70),(3,'MATH','VERY GOOD',80);
    alter table student
    add constraint fk_id
    foreign key (level_id)
    REFERENCES levell (student_id);
    select name from student
    where name like 'A%';
    SELECT * FROM STUDENT
    WHERE birth_d <'1991-10-01' AND gender='MALE';
    DELETE FROM STUDENT
    WHERE student_id IN(SELECT student_id FROM SUBJECT WHERE MAX_SCORE<50 AND NAME='MATH' );
    SELECT S.NAME FROM STUDENT S
    INNER JOIN (SELECT STUDENT_ID FROM SUBJECT 
    ORDER BY MAX_SCORE DESC 
    LIMIT 1 OFFSET 2)E ON S.STUDENT_ID=E.STUDENT_ID;
    SELECT S.NAME,L.NAME FROM STUDENT S INNER JOIN
    LEVELL L ON S.STUDENT_ID=L.STUDENT_ID;
    
    
    
    
